name: 'Docker build and push'

on:
  workflow_dispatch:
  push:
    tags: [ 4* ]
  pull_request:
    branches: [ master ]
    tags: [ 4* ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: mablanco/osmedeus

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build Docker image
        uses: docker/build-push-action@v4.2.1
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # - name: Push Docker image
      #   uses: docker/build-push-action@v4.2.1
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}

      - name: Scan image for vulnerabilities
        uses: anchore/scan-action@v3.3.6
        with:
          image: ${{ steps.meta.outputs.tags }}
          fail-build: false
          only-fixed: true

      - name: Inspect SARIF report
        run: cat ${{ steps.scan.outputs.sarif }}

      - name: Upload scan SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
